name: Parallel Test.py Runs and Commit

on:
  push:
    branches:
      - khoi

jobs:
  run-parallel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - a: 0
            b: 10
          - a: 10
            b: 20
          - a: 20
            b: 30

    outputs:
      result_files: ${{ steps.set-outputs.outputs.files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run test.py with matrix inputs
        run: |
          python test_1.py ${{ matrix.a }} ${{ matrix.b }} output_${{ matrix.a }}_${{ matrix.b }}.txt

      - name: Upload result file
        uses: actions/upload-artifact@v4
        with:
          name: output_${{ matrix.a }}_${{ matrix.b }}
          path: output_${{ matrix.a }}_${{ matrix.b }}.txt

  commit-results:
    needs: run-parallel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: results

      - name: Move results to root (optional)
        run: |
          find results -name "*.txt" -exec mv {} . \;

      - name: Commit and push results
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *.txt
          timestamp=$(date -u)
          git commit -m "Add results from matrix run at $timestamp" || echo "No changes to commit"
          git push
